### ISSUE TITLE
Wrong exception handling when loading dataset from local disk

### ISSUE THREAD

**Issue by ganler** [huggingface/alignment-handbook#173]
https://github.com/huggingface/alignment-handbook/blob/606d2e954fd17999af40e6fb4f712055ca11b2f0/src/alignment/data.py#L216-L221

Actual exception is `ValueError`:

```
[rank5]: Traceback (most recent call last):
[rank5]:   File "run_sft.py", line 251, in <module>
[rank5]:     main()
[rank5]:   File "run_sft.py", line 86, in main
[rank5]:     raw_datasets = get_datasets(
[rank5]:   File "miniconda3/envs/handbook/lib/python3.10/site-packages/alignment/data.py", line 169, in get_datasets
[rank5]:     raw_datasets = mix_datasets(
[rank5]:   File "miniconda3/envs/handbook/lib/python3.10/site-packages/alignment/data.py", line 218, in mix_datasets
[rank5]:     dataset = load_dataset(ds, ds_config, split=split)
[rank5]:   File "miniconda3/envs/handbook/lib/python3.10/site-packages/datasets/load.py", line 2570, in load_dataset
[rank5]:     raise ValueError(
[rank5]: ValueError: You are trying to load a dataset that was saved using `save_to_disk`. Please use `load_from_disk` instead.
```

Dataset version:

```
❯ pip show datasets
Name: datasets
Version: 2.19.1
Summary: HuggingFace community-driven open-source library of datasets
Home-page: https://github.com/huggingface/datasets
Author: HuggingFace Inc.
Author-email: thomas@huggingface.co
License: Apache 2.0
Location: /home/ec2-user/miniconda3/envs/handbook/lib/python3.10/site-packages
Requires: aiohttp, dill, filelock, fsspec, huggingface-hub, multiprocess, numpy, packaging, pandas, pyarrow, pyarrow-hotfix, pyyaml, requests, tqdm, xxhash
Required-by: alignment-handbook, evaluate, trl
```

Also tried the latest `2.19.2` and got the same error. Need to broaden the exceptions to capture.

**Comment by alvarobartt** [comment]
Hi here @ganler, thanks for reporting! Do you want to open a PR to fix the data loading handling? Otherwise, feel free to ping us and we can have a look at it, but as you're pointing out, the following should do the work:

```diff
-     except DatasetGenerationError:
+     except ValueError:
```

Thanks in advance! 🤗

**Comment by ganler** [comment]
Thanks! That's how I fixed it temporarily. Feel free to fix it on your side.

**Comment by xiyang-aads-lilly** [comment]
seems that this issue has not been fixed in the repo https://github.com/huggingface/alignment-handbook/blob/01f29c13253ee9b699daf37332e8ccdd016e6890/src/alignment/data.py#L219.
